# Generated by Django 4.0.3 on 2022-03-19 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Annure'), ('U', 'Unpaid'), ('F', 'Family Event'), ('S', 'Special')], default='A', max_length=1, verbose_name='연차 종류')),
                ('days', models.IntegerField(verbose_name='부여된 휴가 일수')),
                ('start_date', models.DateTimeField(verbose_name='휴가 시작일')),
                ('end_date', models.DateTimeField(verbose_name='휴가 종료일')),
                ('approve', models.BooleanField(verbose_name='휴가 승인 여부')),
                ('cancel', models.BooleanField(verbose_name='휴가 취소 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='대상 유저')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Annure'), ('U', 'Unpaid'), ('F', 'Family Event'), ('S', 'Special')], default='A', max_length=1, verbose_name='연차 종류')),
                ('days', models.IntegerField(verbose_name='부여된 휴가 일수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='대상 유저')),
            ],
        ),
    ]
